/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    LanguageChange: typeof import('./src/components/LanguageChange.vue')['default']
    LeaguesTable: typeof import('./src/components/LeaguesTable.vue')['default']
    MatchCard: typeof import('./src/components/MatchCard.vue')['default']
    MatchesList: typeof import('./src/components/MatchesList.vue')['default']
    MatchesTable: typeof import('./src/components/LeaguesTable.vue')['default']
    MatchStatusSwitch: typeof import('./src/components/MatchStatusSwitch.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamCard: typeof import('./src/components/TeamCard.vue')['default']
    TeamsTable: typeof import('./src/components/TeamsTable.vue')['default']
    ThemeChange: typeof import('./src/components/ThemeChange.vue')['default']
  }
}
