/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppFooterMob: typeof import('./src/components/AppFooterMob.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppHeaderMob: typeof import('./src/components/AppHeaderMob.vue')['default']
    DateFilter: typeof import('./src/components/DateFilter.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    DatePickerButton: typeof import('./src/components/DatePickerButton.vue')['default']
    LanguageChange: typeof import('./src/components/LanguageChange.vue')['default']
    Leagues: typeof import('./src/components/Leagues.vue')['default']
    Matches: typeof import('./src/components/Matches.vue')['default']
    MatchesList: typeof import('./src/components/MatchesList.vue')['default']
    MatchesTable: typeof import('./src/components/MatchesTable.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Teams: typeof import('./src/components/Teams.vue')['default']
    ThemeChange: typeof import('./src/components/ThemeChange.vue')['default']
  }
}
